import json
with open('backend/audit_v11_raw_data.json', 'r') as f:
    data = json.load(f)

total_pnl = sum(r['total_pnl'] for r in data)
pnl_buy = sum(r['pnl_buy'] for r in data)
pnl_sell = sum(r['pnl_sell'] for r in data)
profitable_days = len([r for r in data if r['total_pnl'] > 0])
losing_days = len([r for r in data if r['total_pnl'] < 0])
total_trades = sum(r['trades'] for r in data)
total_missed = sum(r['missed'] for r in data)
total_ai = sum(r.get('filtered_ai', 0) for r in data)
total_flux = sum(r.get('filtered_flux', 0) for r in data)
total_sent = sum(r.get('filtered_sent', 0) for r in data)

print(f"Total PnL: {total_pnl:.2f}")
print(f"Buy PnL: {pnl_buy:.2f}")
print(f"Sell PnL: {pnl_sell:.2f}")
print(f"Profitable Days: {profitable_days}")
print(f"Losing Days: {losing_days}")
print(f"Total Trades: {total_trades}")
print(f"Total Missed: {total_missed}")
print(f"Filtered by AI: {total_ai}")
print(f"Filtered by Flux: {total_flux}")
print(f"Filtered by Sentiment: {total_sent}")
